### ISSUE TITLE
Terraform Vars Cascade Processing

### ISSUE THREAD

**Issue by Tensho** [gruntwork-io/terragrunt-infrastructure-live-example#16]
Does it make sense to process `terraform.tfvars` files in **all** parent directories? Consider the next example:
```
prod
  us-east-1
    prod
      mysql
        terraform.tfvars # 1 (particular module level variables)
  terraform.tfvars # 2 (region level variable)
terraform.tfvars # 3 (account level variables)
```
Currently, there is only `find_in_parent_folders()`, which picks the first found `terraform.tfvars` file in the parent directories. In the example above we can merge only 1 and 2. It would be nice to adjust the function or create a new one  (to not break backward compatibility), which would merge 1, 2, and 3.

[People achieve described behavior with the hooks](https://github.com/antonbabenko/terragrunt-reference-architecture/blob/master/acme-prod/terraform.tfvars#L7), but I think that should be in the "core".

**Comment by yorinasub17** [comment]
Hi can you reopen this ticket on the `terragrunt` repo? (https://github.com/gruntwork-io/terragrunt). This repo is an example of how to use terragrunt, and so the issues are for reporting specific bugs in the example. This looks like a feature request for `terragrunt` itself, so doesn't really belong here.

Closing this ticket given above. Thanks and sorry for the extra steps.

**Comment by Tensho** [comment]
@yorinasub17 NP, thanks for referencing 🙇
