### ISSUE TITLE
VPC for multi-regions?

### ISSUE THREAD

**Issue by luckytaxi** [gruntwork-io/terragrunt-infrastructure-live-example#22]
I understand keeping the examples simple, but I'm curious as to how to handle VPCs for each region? Is there an example of how I would be able to deploy VPCs for two regions within the same account?

**Comment by yorinasub17** [comment]
We have an example for this for Gruntwork customers, but if not unfortunately we don't. With that said, the way to do this is to create another folder at the region level (e.g `us-east-2` next to `us-east-1`) and add in the `region.yaml` file pointing to the new region. Then, all modules in that folder will automatically get the updated region passed in.

**Comment by luckytaxi** [comment]
So this doesn't appear to work for me.

I'm not sure where I should be setting `region`. Here's the prompt I get. Once i input a region, it appears to be working correctly

```
provider.aws.region
  The region where AWS operations will take place. Examples
  are us-east-1, us-west-2, etc.
```

```
{~/tf-infrastructure/sandbox/us-west-2}-> cat region.yaml
aws_region: "us-west-2"
```

**Comment by yorinasub17** [comment]
You want to expose `aws_region` as a variable in your terraform file and then feed it to the provider:

```
provider "aws" {
  region = var.aws_region
}
```
