### ISSUE TITLE
Represent map in the yaml file

### ISSUE THREAD

**Issue by joshtharakan** [gruntwork-io/terragrunt-infrastructure-live-example#27]
Please share how we can mention a map variable like tags in the `xxx.yaml` file. 

I tried with the below but it failed with the error below

xxx.yaml
``` 
tags : 
  Terraform   : "true"
  Project     : "ics-dlt"
  Environment : "common"

```

error
```Error: Incorrect attribute value type

  on .terraform/modules/remote_state/dynamo.tf line 21, in resource "aws_dynamodb_table" "lock":
  21:   tags = var.tags
    |----------------
    | var.tags is "{\"Environment\":\"common\",\"Project\":\"ics-dlt\",\"Terraform\":\"true\"}"

Inappropriate value for attribute "tags": map of string required.
```

**Comment by yorinasub17** [comment]
Please see https://github.com/gruntwork-io/terragrunt/issues/1007, https://github.com/gruntwork-io/terragrunt/issues/997, and https://github.com/gruntwork-io/terragrunt/issues/1002. You need to add the `type` information to the `annotations` variable in terraform, `type = map(map(string))`.

**Comment by joshtharakan** [comment]
thanks @yorinasub17. that worked
