### ISSUE TITLE
Why need prod under us-east-1?

### ISSUE THREAD

**Issue by tmpm697** [gruntwork-io/terragrunt-infrastructure-live-example#35]
```
├── prod
│   ├── account.hcl
│   └── us-east-1
│       ├── prod
│       │   ├── env.hcl
│       │   ├── mysql
│       │   │   └── terragrunt.hcl
│       │   └── webserver-cluster
│       │       └── terragrunt.hcl
│       └── region.hcl
```

Why we need `prod` under `us-east-1`? (us-east-1/prod)

What is the use-case for?

I can image that we can have services in prod in multiple regions but why separate under region what is in prod or not?

**Comment by yorinasub17** [comment]
See https://github.com/gruntwork-io/terragrunt-infrastructure-live-example#how-is-the-code-in-this-repo-organized , specifically the bullet regarding `Environment`.
