### ISSUE TITLE
[QUESTION] Dependency in _global folder

### ISSUE THREAD

**Issue by timkra** [gruntwork-io/terragrunt-infrastructure-live-example#36]
Hi,

I´m working on implementing this repository structure for my own project. 
The documentation states that there can be a _global folder for resources like IAM. 

My question would be, how can I implement a dependency of a resource in the _global folder to a resource in an environment folder

My terragrunt.hcl in the environment folder has the following config
```
.
.
.
include {
  path = find_in_parent_folders()
}

# Set Module dependencies
dependencies {
  paths =  [
    "../../../_global/tf-iam"
    ]
}
```
When running the plan-all command in the environment folder i get the following error message.

```
Module /home/ec2-user/aws-account-name/eu-central-1/dev/tf-ec2 ../../../_global/tf-iam as a dependency, but that dependency was not one of the ones found while scanning subfolders:
```
Any help would be appreciated.
Thanks!

**Comment by yorinasub17** [comment]
You can pass in the [--terragrunt-include-external-dependencies](https://terragrunt.gruntwork.io/docs/reference/cli-options/#terragrunt-include-external-dependencies) flag.

**Comment by timkra** [comment]
@yorinasub17 , thank you for your fast response!
This works like a charm.
