### ISSUE TITLE
Needs update on terraform GH sources for modules

### ISSUE THREAD

**Issue by darpham** [gruntwork-io/terragrunt-infrastructure-live-example#38]
This live example is currently broken without the latest commits being included in the latest modules from the [modules-example](https://github.com/gruntwork-io/terragrunt-infrastructure-modules-example) repository.

You can see more details on the issue I [created over there](https://github.com/gruntwork-io/terragrunt-infrastructure-modules-example/issues/15).

Once the changes in the issue above has been addressed, we will need to update the `Terraform Sources` for the modules.

Thanks!

**Comment by yorinasub17** [comment]
This is now fixed.
