### ISSUE TITLE
Can't use aws profile without setting AWS_PROFILE environment variable

### ISSUE THREAD

**Issue by arthurazr777** [gruntwork-io/terragrunt-infrastructure-live-example#48]
Hi,
Since in account.hcl I use the aws_profile varible, I would like that when running terragrunt that profile will be used without the need to set an AWS_PROFILE environment variable, so I added it to the root terragrunt.hcl file in the backend s3 remote state but it doesn't work without setting the AWS_PROFILE environment variable.
Since that aws_profile variable is specified I am guessing this should be a working feature in the project, I appreciate the project and the help with this issue, thank you.

This is the error I get:

> Initializing modules...
> 
> Initializing the backend...
> 
> Error: error configuring S3 Backend: no valid credential sources for S3 Backend found.
> 
> Please see https://www.terraform.io/docs/backends/types/s3.html
> for more information about providing credentials.
> 
> Error: NoCredentialProviders: no valid providers in chain. Deprecated.
> 	For verbose messaging see aws.Config.CredentialsChainVerboseErrors
> 
> [terragrunt] 2020/10/23 23:49:20 Hit multiple errors:
> exit status 1

Attached my code:

```
locals {
  account_vars = read_terragrunt_config(find_in_parent_folders("account.hcl"))
  region_vars = read_terragrunt_config(find_in_parent_folders("region.hcl"))
  environment_vars = read_terragrunt_config(find_in_parent_folders("env.hcl"))
  account_name = local.account_vars.locals.account_name
  account_id   = local.account_vars.locals.aws_account_id
  aws_profile  = local.account_vars.locals.aws_profile
  aws_region   = local.region_vars.locals.aws_region
}

generate "provider" {
  path      = "provider.tf"
  if_exists = "overwrite_terragrunt"
  contents  = <<EOF
provider "aws" {
  region = "${local.aws_region}"
  profile = "${local.aws_profile}"
  allowed_account_ids = ["${local.account_id}"]
}
EOF
}

remote_state {
  backend = "s3"
  config = {
    profile        = local.aws_profile
    encrypt        = true
    bucket         = "${get_env("TG_BUCKET_PREFIX", "")}blablabla777-${local.account_name}-${local.aws_region}"
    key            = "${path_relative_to_include()}/terraform.tfstate"
    region         = local.aws_region
    dynamodb_table = "terraform-locks"
  }
  generate = {
    path      = "backend.tf"
    if_exists = "overwrite_terragrunt"
  }
}
inputs = merge(
  local.account_vars.locals,
  local.region_vars.locals,
  local.environment_vars.locals,
)
```

**Comment by brikis98** [comment]
Is `local.aws_profile` set correctly? Can you check in the generated `backend.tf`?

**Comment by arthurazr777** [comment]
Hi, yes I checked and it is being set correctly

**Comment by brikis98** [comment]
Could you try one more thing? Go into the folder where the `backend.tf` is generated, and try running `terraform init`. In other words, this takes Terragrunt totally out of the equation.

**Comment by arthurazr777** [comment]
I don't know why but everything started to work, possibly had an issue with the cache or in the previous terminal session, thank you.
