### ISSUE TITLE
Getting error for "AWS Account ID not allowed"

### ISSUE THREAD

**Issue by avnerenv0** [gruntwork-io/terragrunt-infrastructure-live-example#50]
Hi I have an issue trying to run this out of the box - I get the error `AWS Account ID not allowed:`
After some digging around I understood that I need to change `account.hcl`

I was wondering about two things - 
1. Should this be added to the README as it is not mentioned anywhere except the comment in the file itself?
2. Is there a way to inject this var using an environment variable or something like that, so it wouldn't be necessary to change the files?

Thanks

**Comment by brikis98** [comment]
> 1. Should this be added to the README as it is not mentioned anywhere except the comment in the file itself?

Yes please! Would you be up for a quick PR to add this?

> 2. Is there a way to inject this var using an environment variable or something like that, so it wouldn't be necessary to change the files?

There is, but you most likely won't want to. The main use of the account ID is to ensure you're deploying to the right account. Hard-coding that value in a file provides that protection (albeit at the cost of a little extra work up front). Reading that value from an environment variable makes it too likely you'll happen to have the wrong value set.
