### ISSUE TITLE
Why are there two "prod" folders in the directory tree?

### ISSUE THREAD

**Issue by trallnag** [gruntwork-io/terragrunt-infrastructure-live-example#54]
Looking at the directory tree I am seeing two "prod" dirs on two different levels? What is the reason for this layout?

![image](https://user-images.githubusercontent.com/24834206/107766951-8e6a7300-6d34-11eb-8da5-b90881cd73e5.png)

**Comment by bwhaley** [comment]
The top level `prod` represents an AWS account called "prod". It contains all the configurations for the prod AWS account in all regions. The nested `prod` represents a VPC called "prod" in the `us-east-1` region. It contains all the configuration for resources in the prod account, us-east-1 region, prod VPC.

The reasoning behind this layout is that you can have fine-grained control over what configurations are applied. For example, you could run `terragrunt run-all apply` (formerly `terragrunt apply-all`) at the `prod/us-east-1/prod` level to apply only the configurations in the prod vpc, us-east-1 region, prod account. Or, you could run the same command but at the `prod/us-east-1` level to apply all the configurations for the prod account, us-east-1 region. You can think of it as a hierarchy that allows you to have control over what configurations are applied at any given time.

**Comment by trallnag** [comment]
@bwhaley, makes sense. Thanks for the explanation. I guess in my use case I just don't need such a layout because I use the Terragrunt live repository for a single product / project only and I know from the start that I only need a single region and VPC (per environment like prod, QA, and dev.

**Comment by bwhaley** [comment]
There are infinite ways to approach the layout so feel free to experiment! We're toying with another approach ourselves as outlined [here](https://github.com/gruntwork-io/terragrunt/issues/1451#issuecomment-737155756).
