### ISSUE TITLE
Error: Terraform initialized in an empty directory

### ISSUE THREAD

**Issue by hammadzz** [gruntwork-io/terragrunt-infrastructure-live-example#7]
I am trying to run an example that is mostly a copy of this repo. My repo is local so I am using the argument on terragrunt plan as `--terragrunt-source /Users/me/Documents/other/projectx/projectx-terraform-modules`. I keep getting issues as below. I have shown the directory structure and I have also gone through the temporary output.

```
Terraform initialized in an empty directory!

The directory has no Terraform configuration files. You may begin working
with Terraform immediately by creating Terraform configuration files.
[terragrunt] 2018/01/21 21:53:00 Running command: terraform plan

Error: No configuration files found!
```

My live repo
```
└── non-prod
    ├── account.tfvars
    ├── terraform.tfvars
    └── us-east-1
        └── stage
            └── postgresql
                └── terraform.tfvars
```

My modules repo
```
├── postgresql
│   ├── main.tf
│   ├── outputs.tf
│   └── vars.tf
└── vpc
    ├── main.tf
    ├── outputs.tf
    └── vars.tf
```

temp directory created by terra grunt
```
└── iASxrJUmUlXYPnHVRN4NFMJU39g
    ├── account.tfvars
    ├── postgresql
    │   ├── main.tf
    │   ├── outputs.tf
    │   └── vars.tf
    ├── terraform.tfvars
    ├── us-east-1
    │   └── stage
    │       ├── postgresql
    │       │   └── terraform.tfvars
    │       └── postgresql.tfvars
    └── vpc
        ├── main.tf
        ├── outputs.tf
        └── vars.tf
```

**Comment by brikis98** [comment]
What folder are you in when you run Terragrunt?

**Comment by hammadzz** [comment]
I am in `non-prod` when running terragrunt

**Comment by brikis98** [comment]
When you're in the folder of a specific module, you can run `apply` or `plan` and set `--terragrunt-source` to the corresponding module. Example:

```
cd non-prod/us-east-1/stage/postgresql
terragrunt apply --terragrunt-source /Users/me/Documents/other/projectx/projectx-terraform-modules//postgresql
```

If you want to deploy multiple modules at once, you need to use `apply-all` or `plan-all` and set `--terragrunt-source` to the root of your modules repo. Example:

```
cd non-prod
terragrunt apply-all --terragrunt-source /Users/me/Documents/other/projectx/projectx-terraform-modules
```

**Comment by brikis98** [comment]
Glad that helped 👍

**Comment by Ulomike70** [comment]
[Terraform-main.zip](https://github.com/gruntwork-io/terragrunt-infrastructure-live-example/files/9246110/Terraform-main.zip)
